version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build:
      context: .
    image: sidhu1504/myflaskapp:latest   # 👈 this is your Docker Hub repo
    ports:
      - "9000:8000"
    depends_on:
      - redis
    restart: unless-stopped

